[#ftl]
[@b.head/]
[@b.grid items=profiles var="profile"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col property="name" title="名称" width="10%"]
        [@b.a href="!info?id=${profile.id}"]<span style="font-size:0.8rem;color: #999;">${profile.org.name}.</span>${profile.name!}[/@]
    [/@]
    [@b.col property="title" title="说明" ]${profile.org.shortTitle}${profile.title}[/@]
    [@b.col property="sasVersion" title="版本"  width="8%"]${profile.sasVersion}[/@]
    [@b.col property="ip" title="IP"  width="13%"]${profile.ip!}[/@]
    [@b.col property="hostname" title="域名" width="16%"]${profile.hostname!}[/@]
    [@b.col property="enableHttps" title="使用HTTPS" width="10%"]${profile.enableHttps?c}[/@]
    [@b.col title="负载" width="9%"]
      [#if profile.proxyEngine='haproxy']
        [@b.a href="/"+profile.qualifiedName+"/haproxy.cfg" target="_blank"]haproxy[/@]
      [#else]
        [@b.a href="/"+profile.qualifiedName+"/nginx.conf" target="_blank"]nginx[/@]
      [/#if]
    [/@]
    [@b.col title="配置" width="9%"]
      [@b.a href="/"+profile.qualifiedName+"/server.xml" target="_blank"]查看[/@]
    [/@]
  [/@]
[/@]
[@b.foot/]
