[@b.head/]
[@b.toolbar title="修改或新增组件"]bar.addBack();[/@]
[#assign packagings={'jar':'Jar','war':'War','bin':'Bin'}/]
  [@b.form action=b.rest.save(artifact) theme="list"]
    [@b.textfield label="标题" name="artifact.title" value=artifact.title required="true" maxlength="100" /]
    [@b.textfield label="common.name" name="artifact.artifactId" value=artifact.artifactId!   required="true" maxlength="100" comment="artifactId"/]
    [@b.textfield label="分组" name="artifact.groupId" value=artifact.groupId required="true" maxlength="100" comment="groupId"/]
    [@b.radios label="打包类型" name="artifact.packaging" value=artifact.packaging! required="true" items= packagings comment="packaging"/]
    [@b.textfield label="分类器" name="artifact.classifier" value=artifact.classifier! maxlength="100" comment="classifier"/]
    [@b.textfield label="最新版本" name="artifact.latestVersion" value=artifact.latestVersion required="true" maxlength="100" /]
    [@b.textfield label="默认上下文" name="artifact.contextPath" value=artifact.contextPath! required="true" maxlength="100"/]

    [@b.select label="针对配置" name="artifact.profile.id" value=artifact.profile! items=profiles empty="..." option="id,qualifiedName"/]
    [@b.textarea label="介绍" name="artifact.description" value=artifact.description! required="true"  rows="5" cols="80" maxlength="500"/]
    [@b.radios label="需要解析" name="artifact.resolveSupport" value=artifact.resolveSupport! items="1:支持,0:不支持" comment="是否包含META-INF/beangle/dependencies"/]
    [@b.radios label="jspSupport" name="artifact.jspSupport" value=artifact.jspSupport! required="true"  /]
    [@b.radios label="websocketSupport" name="artifact.websocketSupport" value=artifact.websocketSupport!  required="true"/]
    [@b.formfoot]
      [@b.reset/] &nbsp;&nbsp;[@b.submit value="action.submit" /]
    [/@]
  [/@]
[@b.foot/]
