[@b.head/]
[@b.toolbar title="修改或新增组织"]bar.addBack();[/@]

[@b.form action=b.rest.save(org)theme="list"]
  [@b.textfield label="名称" name="org.name" value=org.name! required="true" maxlength="100" /]
  [@b.textfield label="标题" name="org.title" value=org.title! style="width:200px;" required="true" maxlength="100" /]
  [@b.textfield label="简称" name="org.shortTitle" value=org.shortTitle! required="true" maxlength="100" /]
  [@b.textfield label="logoURL" name="org.logoUrl" value=org.logoUrl! required="true" style="width:400px;" /]
  [@b.formfoot]
    [@b.reset/] &nbsp;&nbsp;[@b.submit value="action.submit" /]
  [/@]
[/@]
[@b.foot/]
