[@b.head/]
[@b.toolbar title="修改或新增功能"]bar.addBack();[/@]

[@b.form action=b.rest.save(platformFeature) theme="list"]
  [@b.textfield label="名称" name="platformFeature.name" value=platformFeature.name! required="true" maxlength="100" /]
  [@b.textfield label="logo" name="platformFeature.logo" value=platformFeature.logo! required="true" maxlength="300"  style="width:400px"/]
  [@b.textfield label="版本" name="platformFeature.version" value=platformFeature.version! required="true" maxlength="20" /]
  [@b.select name="dependencyId" items=dependencies required="false" label="依赖" multiple="true" values=platformFeature.dependencies chosenMin="1" style="width:400px"/]
  [@b.textarea label="描述" name="platformFeature.description" value=platformFeature.description! required="true" maxlength="500" cols="80" rows="5"/]
  [@b.formfoot]
    [@b.reset/] &nbsp;&nbsp;[@b.submit value="action.submit" /]
  [/@]
[/@]
[@b.foot/]
