[#ftl]
[@b.head/]
[@b.toolbar title="修改分组"]bar.addBack();[/@]
<style>form.listform label.title{width:120px;}</style>
[@b.tabs]
  [@b.form action=b.rest.save(appGroup) theme="list"]
    [@b.textfield name="appGroup.name" label="名称" value=appGroup.name! required="true" maxlength="200"/]
    [@b.textfield name="appGroup.title" label="标题" value=appGroup.title! required="true" maxlength="200"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
