[@b.head/]
[@b.toolbar title="修改或新增静态上下文"]bar.addBack();[/@]
  [@b.form action=b.rest.save(asset) theme="list"]
    [@b.textfield label="名称" name="asset.name" value=asset.name required="true" maxlength="100" /]
    [@b.textfield label="上下文" name="asset.base" value=asset.base required="true" maxlength="100" /]
    [@b.textfield label="描述" name="asset.remark" value=asset.remark maxlength="100" /]
    [@b.select label="所在组" name="asset.group.id" value=asset.group! items=groups required="true"/]
    [@b.textarea label="bundleUris" name="asset.bundleUris" value=asset.bundleUris!"" required="true"  rows="5" cols="80" maxlength="500"/]
    [@b.formfoot]
      [@b.reset/] &nbsp;&nbsp;[@b.submit value="action.submit" /]
    [/@]
  [/@]
[@b.foot/]
